language: node_js

sudo: false

node_js:
    - "6"

cache:
    directories:
        - node_modules/

branches:
    only:
        - master

script:
    - "npm install standard -g"
    - "./node_modules/.bin/standard"
